# Generated by Django 2.2 on 2020-04-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksAuthors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='note',
            field=models.TextField(default='added notes'),
            preserve_default=False,
        ),
    ]
